### PR TITLE
fix: Change expression to evaluate to a string, rather than a boolean

### PR DESCRIPTION
**Pull request by zachnewburgh**
This pull request has been automatically created by learn.co.

### CODE REVIEW

**Comment by gj** [comment]
Hey @zachnewburgh !

The operators currently in the lesson (`||` and `&&`) are just regular old logical operators — perhaps superseded by the introduction of the ternary to Angular, but definitely not out-of-date. The code still works fine. 🙂

**Comment by zachnewburgh** [comment]
@gj Thanks for following up. Looking at the code, however, the expression should be changed. Otherwise, it'll evaluate to a boolean, rather than a string.

**Comment by gj** [comment]
@zachnewburgh no worries! Test the code out — it evaluates to a string either way.

**Comment by zachnewburgh** [comment]
Hmm, you're right. I had no idea that a ternary could be written like that. Isn't that pretty unconventional syntax, though? Wouldn't it be better to introduce ternaries as they're most commonly written?

`[boolean] ? [expression] : [expression]`

**Comment by gj** [comment]
Nope, not unconventional at all — it just isn't a ternary. Accomplishes the same thing, and you'll see logical operators used in the same manner in many programming languages.

We introduce the ternary operator in both the Ruby and JavaScript sections.

**Comment by zachnewburgh** [comment]
@gj That's funny, I've never seen it. I even showed it to senior developers at work and they were surprised to learn that it evaluated to the string. I'm curious to know why that is. If it's not too much trouble, would you mind forwarding me the relevant documentation? I've never come across that syntax!

**Comment by gj** [comment]
No trouble at all!

Here's the first paragraph of [MDN's introduction to logical operators in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators):
>Logical operators are typically used with Boolean (logical) values. When they are, they return a Boolean value. **However, the && and || operators actually return the value of one of the specified operands, so if these operators are used with non-Boolean values, they may return a non-Boolean value**.

**Pull request closed without merging**
